# Generated by Django 3.1.5 on 2021-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshivenda', models.TextField()),
                ('english', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FreePull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshivenda', models.TextField()),
                ('english', models.TextField()),
            ],
        ),
    ]
